#!/bin/bash

# config
ZONE_DIRECTORY=/etc/bind/zones/master
RECORD_TYPE=A
PARAMS=()

while (( "$#" )); do
  case "$1" in
    -t)
      RECORD_TYPE=$2
      shift 2
      ;;
    *)
      PARAMS+=($1)
      shift
      ;;
  esac
done

case $RECORD_TYPE in
     A)
          DOMAIN=${PARAMS[0]}
          IP=${PARAMS[1]}
          ZONE=${PARAMS[2]}
	  ZONE_NAME=$(echo $ZONE | awk '{sub(/\..*/,x)}1')

	  if [ $ZONE = "bjarne-huijs.sb.uclllabs.be" ]; then
	  	# Add record info
          	echo "$DOMAIN   IN  A       $IP" >> $ZONE_DIRECTORY/db.$ZONE

          	# Increment serial
          	LINE=$(grep -n '; Serial' "$ZONE_DIRECTORY/db.$ZONE" | cut -d : -f 1)
          	OLD_SERIAL=$(sed "${LINE}q;d" $ZONE_DIRECTORY/db.$ZONE | sed -r 's/\s+//g' | sed 's/;.*//')
          	NEW_SERIAL=$(($OLD_SERIAL + 1))
          	sed -i "${LINE}s/.*/           $NEW_SERIAL            ; Serial/" $ZONE_DIRECTORY/db.$ZONE
	  else
          	# Add record info
          	echo "$DOMAIN   IN  A       $IP" >> $ZONE_DIRECTORY/db.$ZONE_NAME

          	# Increment serial
          	LINE=$(grep -n '; Serial' "$ZONE_DIRECTORY/db.$ZONE_NAME" | cut -d : -f 1)
          	OLD_SERIAL=$(sed "${LINE}q;d" $ZONE_DIRECTORY/db.$ZONE_NAME | sed -r 's/\s+//g' | sed 's/;.*//')
          	NEW_SERIAL=$(($OLD_SERIAL + 1))
          	sed -i "${LINE}s/.*/           $NEW_SERIAL		; Serial/" $ZONE_DIRECTORY/db.$ZONE_NAME
	  fi
	  ;;
     CNAME)
          DOMAIN=${PARAMS[0]}
          ZONE=${PARAMS[1]}
	  ZONE_NAME=$(echo $ZONE | awk '{sub(/\..*/,x)}1')

	  if [ $ZONE = "bjarne-huijs.sb.uclllabs.be" ]; then
          	# Add record info
          	echo $DOMAIN       IN CNAME      $ZONE. >> $ZONE_DIRECTORY/db.$ZONE

          	# Increment serial
          	LINE=$(grep -n '; Serial' "$ZONE_DIRECTORY/db.$ZONE" | cut -d : -f 1)
          	OLD_SERIAL=$(sed "${LINE}q;d" $ZONE_DIRECTORY/db.$ZONE | sed -r 's/\s+//g' | sed 's/;.*//')
          	NEW_SERIAL=$(($OLD_SERIAL + 1))
          	sed -i "${LINE}s/.*/           $NEW_SERIAL		; Serial/" $ZONE_DIRECTORY/db.$ZONE
	  else
	  	# Add record info
                echo $DOMAIN       IN CNAME      $ZONE. >> $ZONE_DIRECTORY/db.$ZONE_NAME

                # Increment serial
                LINE=$(grep -n '; Serial' "$ZONE_DIRECTORY/db.$ZONE_NAME" | cut -d : -f 1)
                OLD_SERIAL=$(sed "${LINE}q;d" $ZONE_DIRECTORY/db.$ZONE_NAME | sed -r 's/\s+//g' | sed 's/;.*//')
                NEW_SERIAL=$(($OLD_SERIAL + 1))
                sed -i "${LINE}s/.*/           $NEW_SERIAL              ; Serial/" $ZONE_DIRECTORY/db.$ZONE_NAME
	  fi
	  ;;
     MX)
          DOMAIN=${PARAMS[0]}
          IP=${PARAMS[1]}
          ZONE=${PARAMS[2]}
	  ZONE_NAME=$(echo $ZONE | awk '{sub(/\..*/,x)}1')

	  if [ $ZONE = "bjarne-huijs.sb.uclllabs.be" ]; then
	  	# Add record info
                echo IN  MX  10  $DOMAIN >> $ZONE_DIRECTORY/db.$ZONE
                echo $DOMAIN   IN  A       $IP >> $ZONE_DIRECTORY/db.$ZONE

                # Increment serial
                LINE=$(grep -n '; Serial' "$ZONE_DIRECTORY/db.$ZONE" | cut -d : -f 1)
                OLD_SERIAL=$(sed "${LINE}q;d" $ZONE_DIRECTORY/db.$ZONE | sed -r 's/\s+//g' | sed 's/;.*//')
                NEW_SERIAL=$(($OLD_SERIAL + 1))
                sed -i "${LINE}s/.*/           $NEW_SERIAL              ; Serial/" $ZONE_DIRECTORY/db.$ZONE
	  else
          	# Add record info
          	echo IN  MX  10  $DOMAIN >> $ZONE_DIRECTORY/db.$ZONE_NAME
          	echo $DOMAIN   IN  A       $IP >> $ZONE_DIRECTORY/db.$ZONE_NAME

          	# Increment serial
          	LINE=$(grep -n '; Serial' "$ZONE_DIRECTORY/db.$ZONE_NAME" | cut -d : -f 1)
          	OLD_SERIAL=$(sed "${LINE}q;d" $ZONE_DIRECTORY/db.$ZONE_NAME | sed -r 's/\s+//g' | sed 's/;.*//')
          	NEW_SERIAL=$(($OLD_SERIAL + 1))
          	sed -i "${LINE}s/.*/           $NEW_SERIAL		; Serial/" $ZONE_DIRECTORY/db.$ZONE_NAME
	  fi
	  ;;
     *)
          echo "Unknown record type."
          exit 12;
	  ;;
esac

systemctl reload bind9
